Mike - E11-B1: Create rec req table
ucsb-cs156-f24/proj-rec-f24-08 pull request #35
Opened 2024-11-15 22:04 UTC by Mike-Petrus

Closes #30 

H2 console on localhost
(will need to pull and run on local host if you test yourself)
![20241115_13h57m04s_grim](https://github.com/user-attachments/assets/f859a3fe-bef5-48c8-a473-0449d05de02c)

Visible on dokku:
dokku postgres:connect rec-mike-petrus-dev-db
\dt

![20241115_13h48m04s_grim](https://github.com/user-attachments/assets/9819b3d2-21fe-4410-8fc5-563ef2e99740)

2024-11-15 22:46 UTC, obenedek20 requested changes

2024-11-15 22:46 UTC, obenedek20 commented on .github/workflows/82-kanban-slack-update.yml
Try and revert this file as it is not a part of your PR

2024-11-15 22:46 UTC, obenedek20 commented on src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
> +  private String recommendationType;
Epic specifies that this should be `recommendationTypes`

2024-11-15 22:46 UTC, obenedek20 commented on src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
> +
missing `submissionDate`

2024-11-15 22:46 UTC, obenedek20 commented on src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
> +  private LocalDateTime completionDate;
Also missing a `status` (only shows up on backend)

2024-11-15 22:46 UTC, obenedek20 commented on src/main/resources/db/migration/changes/RecommendationRequest.json
> +    "databaseChangeLog": [
Changes necessary for this page too based on changes to entities page

2024-11-15 23:34 UTC, Mike-Petrus commented
Fixed above issues (status/date, kanban) and updated H2 screenshot

2024-11-16 00:42 UTC, obenedek20 approved these changes

2024-11-20 23:53 UTC, pconrad approved these changes
LGTM!

2024-11-20 23:53 UTC, merged