AW-Epic14-F1: Added placeholders for professor pages
ucsb-cs156-f24/proj-rec-f24-08 pull request #38
Opened 2024-11-16 08:41 UTC by yw2398

Closes #34 

This PR creates placeholder pages for each professor actions: PendingRequestsPage, CompletedReqquestsPage, StatisticsPage. Were added to App.js/AppNavbar.js, with corresponding testcases. 

I currently set the three pages to be visible to all ROLE_ADMINs on the Navbar. Will need to change them to be only visible to ROLE_PROFESSORs after we setup different role configs(ROLE_STUDENT/PROFESSOR)

Dokku: https://rec-dev-yw2398.dokku-08.cs.ucsb.edu

2024-11-17 22:59 UTC, obenedek20 requested changes

2024-11-17 22:59 UTC, obenedek20 commented on .github/workflows/82-kanban-slack-update.yml
>  on:
Try and remove this from the PR as it is unrelated to your changes

2024-11-19 23:00 UTC, obenedek20 submitted a review, later dismissed

2024-11-20 23:55 UTC, pconrad approved these changes
LGTM.   When the placeholders pages are replaced with real pages, we may want to add storybook entries, but we can skip that for now.

2024-11-20 23:56 UTC, merged