Oscar - Eliminates Restaurant, UCSBDates frontend components
ucsb-cs156-f24/proj-rec-f24-08 pull request #42
Opened 2024-11-18 22:41 UTC by obenedek20

2024-11-19 09:01 UTC, divyanipunj reviewed
Everything looks good to me, but I think RecomendationRequestController and RecomendationRequestControllerTest should reflect the changes that Christy recently made. I'm not entirely sure but if this PR gets merged after Christy's PR gets merged, won't it replace the code that she wrote? I could be wrong - let me know what you think. 

I also left this comment on your other PR (#41).

2024-11-19 17:01 UTC, obenedek20 commented
> Everything looks good to me, but I think RecomendationRequestController and RecomendationRequestControllerTest should reflect the changes that Christy recently made. I'm not entirely sure but if this PR gets merged after Christy's PR gets merged, won't it replace the code that she wrote? I could be wrong - let me know what you think.
> 
> I also left this comment on your other PR (#41).

Just pulled from Christy's so should be completely up to date!

2024-11-19 22:21 UTC, divyanipunj approved these changes, later dismissed

2024-11-21 00:46 UTC, pconrad requested changes
Ok… so #41 is all entangled with #39… which needs a major refactor… in ways that are unnecessary.   I’ve put comments on the PR showing a better way to get to your goal so that this PR can be independent of the others. (edited) 




Similarly, this PR is entangled with #41, which is also unnecessary.  If you remove the backend without first removing the frontend for some part of the app, lots of things break (menus and features no longer work).  But it’s fine to remove frontend features without removing the backend… So why, why, why does this PR depend on backend changes?

If it were a clean PR that had started from a fresh copy of main (which should always be your default), it would be mergeable right now (or at least once the commented out code is addressed.)  Instead, in the current form, it’s going to have to wait on a lot of other complicated events.

I suggest redoing it as a clean PR that only removes the frontend code and does nothing else.  That would be mergeable immediately (if it didn't have commented out code.)

2024-11-21 00:46 UTC, pconrad commented on frontend/src/tests/components/Nav/AppNavbar.test.js
> +    // expect(screen.getByText("Welcome,")).toBeInTheDocument();
Commented out code should not be in code that is being merged into main.

```suggestion
```

2024-11-21 04:32 UTC, closed without merging