Oscar - Creates Fixtures for Recommendation Requests (Updated to reflect new controller)
ucsb-cs156-f24/proj-rec-f24-08 pull request #48
Opened 2024-11-20 04:41 UTC by obenedek20

Closes #47 
Merge after #66 - this incorporates the added user_id field inside the database from the new GET and POST controller and db changes PR

Adds a group of three and a single fixture for testing and story purposes with different statuses - professor_id has been added in place of professorEmail and professorName and user_id in place of requesterName to match requested changes by professor Conrad

2024-11-20 05:05 UTC, divyanipunj submitted a review, later dismissed
LGTM!

2024-11-20 06:37 UTC, obenedek20 commented
It says Its waiting for UI Review but then when I click that it says there is nothing to review so I think it is all set

2024-11-20 06:42 UTC, divyanipunj approved these changes, later dismissed
LGTM!

2024-11-20 20:40 UTC, divyanipunj approved these changes, later dismissed

2024-11-21 00:49 UTC, pconrad requested changes
This needs to be adjusted based on the changes to the RecommendationRequest entity and CRUD operations in #39 , so let's hold off until that one is final (or at least nearing it's final form.)

Until then, we won't have a clear idea of what the fields should look like here.

2024-11-21 00:49 UTC, pconrad commented on frontend/src/fixtures/recommendationRequestFixtures.js
> +      professorName: "testname1",
Similar to comments above.

2024-11-22 20:22 UTC, divyanipunj approved these changes, later dismissed
LGTM!

2024-11-24 06:04 UTC, pconrad requested changes
there's only one recommendationType per request, so this should be singular.

2024-11-24 06:04 UTC, pconrad commented on frontend/src/fixtures/recommendationRequestFixtures.js
> +      recommendationTypes: "CS Department BS/MS program",
```suggestion
      recommendationType: "CS Department BS/MS program",
```

2024-11-24 06:04 UTC, pconrad commented on frontend/src/fixtures/recommendationRequestFixtures.js
> +      recommendationTypes: "CS Department BS/MS program",
```suggestion
      recommendationType: "CS Department BS/MS program",
```

2024-11-24 06:04 UTC, pconrad commented on frontend/src/fixtures/recommendationRequestFixtures.js
> +      recommendationTypes: "MS program (other than CS Dept BS/MS)",
```suggestion
      recommendationType: "MS program (other than CS Dept BS/MS)",
```

2024-11-24 06:04 UTC, pconrad commented on frontend/src/fixtures/recommendationRequestFixtures.js
> +      recommendationTypes: "Scholarship or Fellowship",
```suggestion
      recommendationType: "Scholarship or Fellowship",
```

2024-11-24 18:51 UTC, obenedek20 commented
professor_id has been added in place of professorEmail and professorName and user_id in place of requesterName to match requested changes by professor Conrad as well as changing recommendationTypes to recommendationType

2024-11-24 19:13 UTC, pconrad approved these changes
LGTM!

2024-11-24 19:13 UTC, merged