Caleb-Add roles for Professor and Student (precursor to F12 and Epic14-B1) + TESTS
ucsb-cs156-f24/proj-rec-f24-08 pull request #60
Opened 2024-11-21 03:41 UTC by caleb-stahl

**Additions**

1. Adding Professor and Student fields to the users table so in future issues we tackle (F12 and Epic 14-B1) we can use them for roles in the project-rec application
2. Made changes to the the User.java, SecurityConfig.java, userFixtures.java files for project-rec. These changes add code that adds fields for the roles as well as code that handles the roles. 
3. Create two files, RoleInterceptor.java and RoleInterceptorConfig.java, which handle dynamically changing the roles. 
4. Added RoleInterceptorTest.java which tests these new interceptor files. 
5. You will also note changes to the package.json folder in the frontend. This was created so that Storybook changes could be published to pass some of the GH actions tests. 

Closes #59

2024-11-21 04:29 UTC, obenedek20 requested changes

2024-11-21 04:29 UTC, obenedek20 commented on frontend/package.json
> +    "chromatic": "npx chromatic --project-token=chpt_70630482feb0e8b --patch-build=Caleb-B1...main"
I think we probably don't want to commit this as it specifies your branch build - could you revert it and just keep it locally?

2024-11-22 00:55 UTC, obenedek20 approved these changes
LGTM

2024-11-24 19:28 UTC, pconrad approved these changes
LGTM

2024-11-24 19:28 UTC, merged