Oscar - Eliminates Backend Files for Restaurant, UCSBDiningCommons, UCSBDates (New PR from main)
ucsb-cs156-f24/proj-rec-f24-08 pull request #61
Opened 2024-11-21 04:23 UTC by obenedek20

Closes #19 

Dokku: https://rec-obenedek20-dev.dokku-08.cs.ucsb.edu/

You should see that all references/api routes to restaurants, UCSBDates, and ucsbdiningcommons are removed
This is a new version of the PR from earlier that is now closed (PR #41) that is branched straight from main and does not rely on PR #39

2024-11-22 00:39 UTC, divyanipunj submitted a review, later dismissed
LGTM - the new files seem to properly implement what the professor requested.

2024-11-24 05:48 UTC, pconrad requested changes
Please move the DummyController to the test hierarchy.

2024-11-24 05:48 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/DummyController.java
> +package edu.ucsb.cs156.rec.controllers;
Please move `src/main/java/edu/ucsb/cs156/rec/controllers/DummyController.java` to 
`src/test/java/edu/ucsb/cs156/rec/controllers/DummyController.java`.

It is not a real controller, and exists only to help with test coverage.  So it should not be under `/src/main/java` but under `/src/test/java`.  That way it doesn't really show in the real app; only when testing.

2024-11-24 19:15 UTC, pconrad approved these changes
LGTM!

2024-11-24 19:15 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/rec/controllers/DummyController.java
> +package edu.ucsb.cs156.rec.controllers;
See: https://ucsb-cs156-f24.slack.com/archives/C080JHJN9QE/p1732427414430999

2024-11-24 19:23 UTC, merged